// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ActionsCellRenderer: typeof import("./src/components/DataTable/CellRenderers/ActionsCellRenderer.vue")["default"];
    CollapseButton: typeof import("./src/components/Utils/CollapseButton.vue")["default"];
    ComponentCellRenderer: typeof import("./src/components/DataTable/CellRenderers/ComponentCellRenderer.vue")["default"];
    DataGrid: typeof import("./src/components/DataGrid/DataGrid.vue")["default"];
    DataGridItem: typeof import("./src/components/DataGrid/DataGridItem.vue")["default"];
    DataTable: typeof import("./src/components/DataTable/DataTable.vue")["default"];
    DescriptionPopup: typeof import("./src/components/Utils/DescriptionPopup.vue")["default"];
    FieldRenderer: typeof import("./src/components/Form/Field/FieldRenderer.vue")["default"];
    FilterPanel: typeof import("./src/components/DataTable/FilterPanel.vue")["default"];
    FormRenderer: typeof import("./src/components/Form/Field/FormRenderer.vue")["default"];
    JsxCellRenderer: typeof import("./src/components/DataTable/CellRenderers/JsxCellRenderer.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchQueryInput: typeof import("./src/components/DataTable/SearchQueryInput.vue")["default"];
    SelectionHeaderRenderer: typeof import("./src/components/DataTable/CellRenderers/SelectionHeaderRenderer.vue")["default"];
    TableFooter: typeof import("./src/components/DataTable/TableFooter.vue")["default"];
    TableHeader: typeof import("./src/components/DataTable/TableHeader.vue")["default"];
  }
}
