// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionsCellRenderer: typeof import('./src/components/DataTable/CellRenderers/ActionsCellRenderer.vue')['default']
    ComponentCellRenderer: typeof import('./src/components/DataTable/CellRenderers/ComponentCellRenderer.vue')['default']
    DataTable: typeof import('./src/components/DataTable/DataTable.vue')['default']
    FilterPanel: typeof import('./src/components/DataTable/FilterPanel.vue')['default']
    'I:la:search': typeof import('~icons/la/search')['default']
    'I:mdiChevronDown': typeof import('~icons/mdi/chevron-down')['default']
    'I:mdiFilter': typeof import('~icons/mdi/filter')['default']
    'I:mdiFilterVariant': typeof import('~icons/mdi/filter-variant')['default']
    'I:mdiRefresh': typeof import('~icons/mdi/refresh')['default']
    'I:systemUicons:reset': typeof import('~icons/system-uicons/reset')['default']
    JsxCellRenderer: typeof import('./src/components/DataTable/CellRenderers/JsxCellRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchQueryInput: typeof import('./src/components/DataTable/SearchQueryInput.vue')['default']
    SelectionHeaderRenderer: typeof import('./src/components/DataTable/CellRenderers/SelectionHeaderRenderer.vue')['default']
    TableFooter: typeof import('./src/components/DataTable/TableFooter.vue')['default']
    TableHeader: typeof import('./src/components/DataTable/TableHeader.vue')['default']
  }
}
