/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Lazy: typeof import('~icons/la/zy')['default']
    'MaterialSymbols:openInBrowser': typeof import('~icons/material-symbols/open-in-browser')['default']
    'MaterialSymbols:settingsBRoll': typeof import('~icons/material-symbols/settings-b-roll')['default']
    'Mdi:arrowLeft': typeof import('~icons/mdi/arrow-left')['default']
    'Mdi:arrowRight': typeof import('~icons/mdi/arrow-right')['default']
    'Mdi:check': typeof import('~icons/mdi/check')['default']
    'Mdi:chevronLeft': typeof import('~icons/mdi/chevron-left')['default']
    'Mdi:chevronRight': typeof import('~icons/mdi/chevron-right')['default']
    'Mdi:eye': typeof import('~icons/mdi/eye')['default']
    'Mdi:import': typeof import('~icons/mdi/import')['default']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
