/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Mdi:chevronLeft': typeof import('~icons/mdi/chevron-left')['default']
    'Mdi:chevronRight': typeof import('~icons/mdi/chevron-right')['default']
    'Mdi:import': typeof import('~icons/mdi/import')['default']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
